a1: c_cons.cpp File Reference
c_cons.cpp File Reference
#include "c_cons.h"
#include "Cell.hpp"
#include "eval.hpp"
#include <stack>
Functions
CCell * c_make_int (const int i)
Make an int cell.
CCell * c_make_double (const double d)
Make a double cell.
CCell * c_make_symbol (const char *const s)
Make a symbol cell.
CCell * c_cons (CCell *const my_car, CCell *const my_cdr)
Make a conspair cell.
void c_delete (CCell *tcell)
Delete the Cell tcell.
Detailed Description
Implementation of the wrapper functions for the C++ functions in Cell.hpp.
Function Documentation
CCell* c_cons (CCell *const my_car, CCell *const my_cdr)
Make a conspair cell.
Parameters:
my_car The initial car pointer to be stored in the new cell.
my_cdr The initial cdr pointer to be stored in the new cell.
References cons().
void c_delete (CCell * tcell)
Delete the Cell tcell.
Parameters:
tcell The Cell to be deleted.
CCell* c_make_double (const double d)
Make a double cell.
Parameters:
d The initial double value to be stored in the new cell.
References make_double().
CCell* c_make_int (const int i)
Make an int cell.
Parameters:
i The initial int value to be stored in the new cell.
References make_int().
CCell* c_make_symbol (const char *const s)
Make a symbol cell.
Parameters:
s The initial symbol name to be stored in the new cell.
References make_symbol().