# This is an example of using simple turtle 
# commands to draw a funny face.

import turtle

turtle.speed(0)
turtle.pensize(3)
turtle.left(90)

# Two eyes
turtle.circle(66)
turtle.right(180)
turtle.circle(66)

# Right eyeball
turtle.up()
turtle.left(90)
turtle.forward(33)
turtle.right(90)
turtle.forward(34)
turtle.down()
turtle.fillcolor("cyan")
turtle.begin_fill()
turtle.circle(33)
turtle.end_fill()
turtle.up()
turtle.forward(15)
turtle.left(90)
turtle.forward(4)
turtle.right(90)
turtle.down()
turtle.fillcolor("black")
turtle.begin_fill()
turtle.circle(11)
turtle.end_fill()

# Left eyeball
turtle.up()
turtle.goto(0, 0)
turtle.left(270)
turtle.forward(33)
turtle.left(90)
turtle.forward(34)
turtle.left(180)
turtle.down()
turtle.fillcolor("cyan")
turtle.begin_fill()
turtle.circle(33)
turtle.end_fill()
turtle.up()
turtle.backward(15)
turtle.right(90)
turtle.backward(4)
turtle.left(90)
turtle.down()
turtle.fillcolor("black")
turtle.begin_fill()
turtle.circle(11)
turtle.end_fill()

# Mouth
turtle.up()
turtle.goto(0, 0)
turtle.right(180)
turtle.forward(70)
turtle.down()
turtle.forward(30)
turtle.circle(30, 180)
turtle.up()
turtle.right(180)
turtle.circle(-30, -180)
turtle.left(180)
turtle.down()
turtle.circle(-30, 180)
turtle.right(180)
turtle.circle(30, 90)
turtle.right(90)
turtle.fillcolor("red")
turtle.begin_fill()
turtle.circle(30, 180)
turtle.end_fill()

# Dots
turtle.up()
turtle.goto(0, 0)
turtle.backward(110)
turtle.left(90)
turtle.forward(20)
turtle.down()
turtle.forward(1)
turtle.up()
turtle.forward(19)
turtle.down()
turtle.forward(1)
turtle.up()
turtle.right(180)
turtle.forward(60)
turtle.down()
turtle.forward(1)
turtle.up()
turtle.forward(19)
turtle.down()
turtle.forward(1)
turtle.up()
turtle.right(90)
turtle.forward(10)
turtle.right(90)
turtle.forward(10)
turtle.down()
turtle.forward(1)
turtle.up()
turtle.forward(60)
turtle.down()
turtle.forward(1)

# Ears
turtle.up()
turtle.goto(0, 0)
turtle.right(90)
turtle.forward(80)
turtle.right(90)
turtle.forward(100)
turtle.down()
turtle.left(50)
turtle.circle(-70, 200)
turtle.up()
turtle.goto(0, 0)
turtle.right(120)
turtle.forward(80)
turtle.left(90)
turtle.forward(100)
turtle.down()
turtle.right(50)
turtle.circle(70, 200)

# Face
turtle.up()
turtle.goto(0, 0)
turtle.right(150)
turtle.forward(190)
turtle.left(90)
turtle.forward(40)
turtle.down()
turtle.circle(190, 180)

# Hair
turtle.up()
turtle.goto(0, 0)
turtle.forward(80)
turtle.down()
turtle.circle(50, 60)
turtle.right(180)
turtle.circle(-50, 60)
turtle.right(180)
turtle.circle(-60, 60)
turtle.left(180)
turtle.circle(60, 60)
turtle.left(180)
turtle.circle(-30, 60)
turtle.hideturtle()

turtle.done()
