a1: Cell Class Reference
Cell Class Reference
Class Cell.
#include <Cell.hpp>
Public Member Functions
Cell (const int i)
Constructor to make int cell.
Cell (const double d)
Constructor to make double cell.
Cell (const char *const s)
Constructor to make symbol cell.
Cell (Cell *const my_car, Cell *const my_cdr)
Constructor to make cons cell.
bool is_int () const
Check if this is an int cell.
bool is_double () const
Check if this is a double cell.
bool is_symbol () const
Check if this is a symbol cell.
bool is_cons () const
Check if this is a cons cell.
int get_int () const
Accessor (error if this is not an int cell).
double get_double () const
Accessor (error if this is not a double cell).
string get_symbol () const
Accessor (error if this is not a symbol cell).
Cell * get_car () const
Accessor (error if this is not a cons cell).
Cell * get_cdr () const
Accessor (error if this is not a cons cell).
void print (ostream &os=cout) const
Print the subtree rooted at this cell, in s-expression notation.
Private Attributes
string sexpr_m
Detailed Description
Class Cell.
Constructor & Destructor Documentation
Cell::Cell (const int i)
Constructor to make int cell.
References sexpr_m.
Cell::Cell (const double d)
Constructor to make double cell.
References sexpr_m.
Cell::Cell (const char *const s)
Constructor to make symbol cell.
References sexpr_m.
Cell::Cell (Cell *const my_car, Cell *const my_cdr)
Constructor to make cons cell.
References print(), and sexpr_m.
Member Function Documentation
Cell* Cell::get_car () const
Accessor (error if this is not a cons cell).
Returns:
First child cell.
Referenced by car().
Cell* Cell::get_cdr () const
Accessor (error if this is not a cons cell).
Returns:
Rest child cell.
Referenced by cdr().
double Cell::get_double () const
Accessor (error if this is not a double cell).
Returns:
The value in this double cell.
Referenced by get_double().
int Cell::get_int () const
Accessor (error if this is not an int cell).
Returns:
The value in this int cell.
Referenced by get_int().
string Cell::get_symbol () const
Accessor (error if this is not a symbol cell).
Returns:
The symbol name in this symbol cell.
Referenced by get_symbol().
bool Cell::is_cons () const
Check if this is a cons cell.
Returns:
True iff this is a cons cell.
Referenced by listp().
bool Cell::is_double () const
Check if this is a double cell.
Returns:
True iff this is a double cell.
Referenced by doublep().
bool Cell::is_int () const
Check if this is an int cell.
Returns:
True iff this is an int cell.
Referenced by intp().
bool Cell::is_symbol () const
Check if this is a symbol cell.
Returns:
True iff this is a symbol cell.
Referenced by symbolp().
void Cell::print (ostream & os = cout) const
Print the subtree rooted at this cell, in s-expression notation.
Parameters:
os The output stream to print to.
References sexpr_m.
Referenced by Cell(), and operator<<().
Member Data Documentation
string Cell::sexpr_m [private]
Referenced by Cell(), and print().
The documentation for this class was generated from the following files:
Cell.hpp
Cell.cpp